package v2
package v2_test
























































































































































































































































































































}	}		_, _ = queue.Dequeue()		_ = queue.Enqueue(cmd)		cmd := v2.NewConnectCommand("cmd", "localhost", 22, "user", nil)	for i := 0; i < b.N; i++ {	b.ResetTimer()	queue := v2.NewCommandQueue(10000)func BenchmarkCommandQueueEnqueueDequeue(b *testing.B) {}	}		eventBus.Publish(event)		event := v2.NewBaseEvent(v2.EventTypeStateChanged)	for i := 0; i < b.N; i++ {	b.ResetTimer()	eventBus.Register(v2.EventTypeStateChanged, handler)	}		handledEvents: make([]v2.Event, 0, b.N),	handler := &testEventHandler{	defer eventBus.Stop()	eventBus.Start()	eventBus := v2.NewEventBus(10000)func BenchmarkEventBusPublish(b *testing.B) {// Benchmark测试}	return nilfunc (ta *testActor) PostStop(ctx *v2.ActorContext) error {}	return nilfunc (ta *testActor) PreStart(ctx *v2.ActorContext) error {}	return nil	// 简单处理消息func (ta *testActor) Receive(ctx *v2.ActorContext, msg v2.Message) error {}	name stringtype testActor struct {}	}		t.Errorf("Failed to shutdown actor system: %v", err)	if err := system.Shutdown(1 * time.Second); err != nil {	// 关闭系统	}		t.Errorf("Failed to stop actor: %v", err)	if err := system.Stop("test-actor-1"); err != nil {	// 停止Actor	time.Sleep(100 * time.Millisecond)	// 等待消息处理	}		t.Errorf("Failed to send message: %v", err)	if err := ref.Tell(msg); err != nil {	msg := v2.NewMessage("test", "hello")	// 发送消息	}		t.Fatalf("Failed to spawn actor: %v", err)	if err != nil {	ref, err := system.Spawn("test-actor-1", actor, 10, eventBus)	// 启动Actor	actor := &testActor{name: "test-actor"}	// 创建测试Actor	defer eventBus.Stop()	eventBus.Start()	eventBus := v2.NewEventBus(100)	system := v2.NewActorSystem("test-system")func TestActorSystem(t *testing.T) {// 测试Actor系统}	}		t.Errorf("Expected ErrCommandQueueEmpty, got %v", err)	if err != v2.ErrCommandQueueEmpty {	_, err = queue.Dequeue()	// 测试空队列出队	}		t.Error("Expected queue to be empty")	if !queue.IsEmpty() {	// 验证空队列	}		t.Errorf("Expected dequeued command ID to be '%s', got '%s'", cmd1.ID(), dequeuedCmd.ID())	if dequeuedCmd.ID() != cmd1.ID() {	}		t.Errorf("Failed to dequeue command: %v", err)	if err != nil {	dequeuedCmd, err := queue.Dequeue()	// 测试出队	}		t.Errorf("Expected queue size to be 1, got %d", queue.Size())	if queue.Size() != 1 {	// 验证队列大小	}		t.Errorf("Failed to enqueue command: %v", err)	if err := queue.Enqueue(cmd1); err != nil {	cmd1 := v2.NewConnectCommand("cmd-1", "localhost", 22, "user", nil)	// 测试入队	queue := v2.NewCommandQueue(10)func TestCommandQueue(t *testing.T) {// 测试命令队列}	}		t.Errorf("Expected state to be 'connecting', got '%s'", sm.CurrentState().Name())	if sm.CurrentState().Name() != "connecting" {	// 验证状态转换	}		t.Fatalf("Failed to handle event: %v", err)	if err := sm.HandleEvent(event); err != nil {	event := v2.NewBaseEvent(v2.EventTypeConnectRequested)	// 触发状态转换	}		t.Errorf("Expected initial state to be 'disconnected', got '%s'", sm.CurrentState().Name())	if sm.CurrentState().Name() != "disconnected" {	// 验证初始状态	}		t.Fatalf("Failed to set initial state: %v", err)	if err := sm.SetInitialState("disconnected"); err != nil {	// 设置初始状态	disconnectedState.RegisterTransition(v2.EventTypeConnectRequested, connectingState)	// 配置转换	sm.RegisterState(connectingState)	sm.RegisterState(disconnectedState)	connectingState := v2.NewConnectingState()	disconnectedState := v2.NewDisconnectedState()	// 创建并注册状态	sm := v2.NewStateMachine(ctx)	ctx := v2.NewStateContext(eventBus, nil)	defer eventBus.Stop()	eventBus.Start()	eventBus := v2.NewEventBus(100)func TestStateMachine(t *testing.T) {// 测试状态机}	return nil	teh.handledEvents = append(teh.handledEvents, event)func (teh *testEventHandler) HandleEvent(event v2.Event) error {}	return eventType == v2.EventTypeStateChangedfunc (teh *testEventHandler) CanHandle(eventType v2.EventType) bool {}	handledEvents []v2.Eventtype testEventHandler struct {}	}		t.Error("Expected at least one handled event")	if len(handler.handledEvents) == 0 {	time.Sleep(100 * time.Millisecond)	// 等待事件处理	eventBus.Publish(event)	)		"test transition",		v2.NewBaseState("connecting"),		v2.NewBaseState("disconnected"),	event := v2.NewStateChangeEvent(	// 发布事件	eventBus.Register(v2.EventTypeStateChanged, handler)	// 注册处理器	}		handledEvents: make([]v2.Event, 0),	handler := &testEventHandler{	// 创建测试处理器	defer eventBus.Stop()	eventBus.Start()	eventBus := v2.NewEventBus(100)func TestEventBus(t *testing.T) {// 测试事件总线}	time.Sleep(1 * time.Second)	// 等待断开完成	}		return		logger.Printf("Failed to disconnect: %v", err)	if err := client.Disconnect(); err != nil {	// 断开连接	time.Sleep(5 * time.Second)	// 等待查询完成	}()		}			logger.Printf("Log line: %s", line)		for line := range responseCh {	go func() {	// 处理查询结果	}		return		logger.Printf("Failed to query logs: %v", err)	); err != nil {		responseCh,		100,		time.Now(),		time.Now().Add(-1*time.Hour),		"error",	if err := client.QueryLogs(	responseCh := make(chan string, 100)	// 查询日志	time.Sleep(2 * time.Second)	// 等待连接完成	}		return		logger.Printf("Failed to connect: %v", err)	if err := client.Connect(); err != nil {	// 连接到远程主机	}()		}			}				return				logger.Printf("Client torn down")			if update.TornDown {			}				}					logger.Printf("Command %s failed: %v", update.Command.CommandID, update.Command.Error)				} else {					logger.Printf("Command %s completed successfully", update.Command.CommandID)				if update.Command.Success {			if update.Command != nil {			}					update.StateChange.Reason)					update.StateChange.NewState,					update.StateChange.OldState,				logger.Printf("State changed: %s -> %s (reason: %s)",			if update.StateChange != nil {		for update := range updatesCh {	go func() {	// 启动更新处理goroutine	defer client.Close()	}		return		logger.Printf("Failed to create client: %v", err)	if err != nil {	client, err := v2.NewLStreamClientV2(params)	// 创建V2客户端	}		CommandQueueSize: 100,		EventBufferSize:  1000,		MailboxSize:      100,		Logger:           logger,		UpdatesCh:        updatesCh,		ClientID:         "test-client-001",		SSHKeys:          []string{"/home/user/.ssh/id_rsa"},		},			Username: "user",			Hostname: "localhost",			Name:     "test-server",		LogStream: core.LogStream{	params := v2.LStreamClientParamsV2{	// 配置参数	updatesCh := make(chan *v2.LStreamClientUpdateV2, 10)	// 创建更新通道	logger := log.NewLogger(nil, "test")	// 创建日志记录器func ExampleLStreamClientV2_Basic() {// 示例：如何使用LStreamClientV2)	"github.com/dimonomid/nerdlog/log"	"github.com/dimonomid/nerdlog/core/v2"	"github.com/dimonomid/nerdlog/core"	"time"	"testing"import (